#!/usr/bin/env python3

def factorize(number):
    from sympy import factorint
    factors = factorint(number)
    return factors

import sys

if len(sys.argv) != 2:
    print("Usage: ./factors <file>")
    sys.exit(1)

input_file = sys.argv[1]

try:
    with open(input_file, 'r') as file:
        for line in file:
            n = int(line.strip())
            factors_dict = factorize(n)
            factors_str = '*'.join([f'{key}^{value}' for key, value in factors_dict.items()])
            print(f"{n}={factors_str}")

except FileNotFoundError:
    print(f"Error: File '{input_file}' not found.")
    sys.exit(1)

except ValueError:
    print(f"Error: Invalid data in '{input_file}'. Make sure all lines contain valid natural numbers greater than 1.")
    sys.exit(1)
